[project]
name = "opendatasciencesandbox"
version = "0.1.0"
description = "Experimentation with different data science methods and techniques on different open data"
readme = "README.md"
requires-python = ">=3.11.11"
dependencies = []
